### PR TITLE
Ta bort konto/ Fixa navigation/ Fixa trending bug

### LINKED ISSUE #148: Se till att kontot raderas
Som en användare vill jag kunna välja att radera mitt konto.

### PR DESCRIPTION
**Pull request by mirrenil**
**This PR will:**

- add a function to remove the user from firebase and from firestore
- 
**UPDATE**
@liinneea-a  
- Fix navigation structure
- Changes names on initial routes on navigation stacks to correct name
- Reset navigation history on log out
- Reset navigation history when Loading component is done (so user cant go back to Loading)
- Fix bug with trendingScreen by changing sorting function so list can contain products without reviews (this is what created the bug)

closes #148

### CODE REVIEW

**Review by liinneea-a — APPROVED** [review]
Snyggt!

File: screens/ProfileScreen.tsx [hunk 1]
```diff
@@ -179,7 +179,7 @@ export default function ProfileScreen({
         {
           text: "Ja",
           onPress: () => {
-            deleteUser(userToDelete);
+            removeAccount();
             Alert.alert("Ditt konto har raderats");
             setModalVisible(false);
             navigation.navigate("Signin");
```
Comment (liinneea-a) [inline screens/ProfileScreen.tsx:185]: I discovered a bug. When you delete your account you dont get redirected to signin but you are still in profileStack an Sign in is only added as the latest screen in the stack. The navbar is still there and you can switch between the different tabs. 

Simulator Screen Shot - iPhone SE (3rd generation) - 2023-01-25 at 11 47 48

**Review by liinneea-a — CHANGES_REQUESTED** [review]

**Comment by liinneea-a** [comment]
We should also add so all posts and data related to the user gets deleted too
